config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'jets#index'
  resources :jets do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
  resources :search_airports, only: [:index]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :jets

  validates :name, presence: true
  validates :acronym, presence: true
  validates :lat, presence: true
  validates :lon, presence: true

  default_scope { order(:acronym) }

  def code_name
    [acronym, name].join(" - ")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :jet

  validates :seats, presence: true
end

app/models/jet.rb
class Jet < ApplicationRecord

  belongs_to :user
  belongs_to :airport_origin, class_name: "Airport"
  belongs_to :airport_destination, class_name: "Airport"

  has_many :bookings, dependent: :destroy
  mount_uploader :photo, PhotoUploader

  validates :price, presence: true
  validates :max_capacity, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :has_service, presence: true
  validates :start_on, presence: true
  validates :end_on, presence: true
  validates :photo, presence: true


  def seat_range
    (1..max_capacity)
  end

  def calculate_price
    price = self.price + ((self.end_on - self.start_on).floor) * 1000
    final_price = price + (calculate_distance([self.airport_origin.lat.to_f,self.airport_origin.lon.to_f],
      [self.airport_destination.lat.to_f,self.airport_destination.lon.to_f])) * 1.2

    return final_price
  end

  def calculate_distance(loc1, loc2)
    rad_per_deg = Math::PI/180  # PI / 180
    rkm = 6371                  # Earth radius in kilometers
    rm = rkm * 1000             # Radius in meters

    dlat_rad = (loc2[0] - loc1[0]) * rad_per_deg  # Delta, converted to rad
    dlon_rad = (loc2[1] - loc1[1]) * rad_per_deg

    lat1_rad, lon1_rad = loc1.map {|i| i * rad_per_deg }
    lat2_rad, lon2_rad = loc2.map {|i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

    return (rm * c)/1000 # Delta in meters
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :booked_jets, through: :bookings, source: :jet
  has_many :owned_jets, dependent: :destroy, class_name: 'Jet'
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  include Pundit

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :destroy]

  def index
    @bookings = policy_scope(Booking).where(user_id: current_user.id)
    .order(created_at: :desc)
  end

  def show
    @booking = Booking.new
    authorize = @booking
  end

  def edit
    authorize @booking
    @jet = @booking.jet
  end

  def new
  end

  def create
    @booking = Booking.new(booking_params)
    @jet = Jet.find(params[:jet_id])
    @booking.jet = @jet
    @booking.user_id = current_user[:id]
    if @booking.seats
      @booking.booking_price = @jet.calculate_price * @booking.seats
    end
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render 'jets/show'
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @jet = @booking.jet
    authorize @booking
    @booking.update!(booking_params)
    @booking.update_attribute(:booking_price, @jet.calculate_price * @booking.seats)
    redirect_to bookings_path
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

private

  def booking_params
    params.require(:booking).permit(:seats)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/jets_controller.rb
class JetsController < ApplicationController
  before_action :find_jet, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @jets = policy_scope(Jet)
    @airports = Airport.all
    @jets = @jets.sample(4)
  end

  def new
    @jet = Jet.new
    @airports = Airport.all
    authorize @jet
  end

  def create
    @jet = Jet.new(jet_params)
    @jet.user = current_user
    authorize @jet
    if @jet.save
      redirect_to jet_path(@jet)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
    @jet_owner = @jet.user
    authorize @jet
  end

  def edit
    authorize @jet
  end

  def update
    authorize @jet
    @jet.update(jet_params)
    redirect_to jet_path(@jet)
  end

  def destroy
    authorize @jet
    @jet.destroy
    redirect_to jets_path
  end

  private

  def jet_params
    params.require(:jet).permit(:name, :description, :has_service, :origin,
      :price, :photo, :airport_origin_id, :airport_destination_id, :start_on, :end_on, :max_capacity)
  end

  def find_jet
    @jet = Jet.find(params[:id])
  end

end

app/controllers/search_airports_controller.rb
class SearchAirportsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def index
    airport_origin_id = params[:airport_origin]
    airport_destination_id = params[:airport_destination]
    @jets = Jet.where(airport_origin_id: airport_origin_id, airport_destination_id: airport_destination_id)
    @markers = @jets.map do |jet|
      {
        lat: jet.airport_origin.lat,
        lng: jet.airport_origin.lon
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fancy_popup(title, options = {})

    # My default options
    options.reverse_merge!(
      id: 'fancy-close'
    )

    render "shared/fancy_popup", title: title, options: options do
      yield
    end
  end

  def fancy_popup_link(title, options = {})
    # My default options
    options.reverse_merge!(
      target: 'fancy-close'
    )

    content_tag(:p) do
      content_tag(:span, title, class: 'fancyalert', data: { target: options[:target] })
    end
  end
end

app/views/bookings/_bookingform.html.erb
<%= simple_form_for [jet, booking] do |f| %>

    <%= f.input :seats, as: :select, collection: jet.seat_range, include_blank: "Please select number of seats", input_html: { style: "width: 100%" } %>
    <%= f.submit "Submit" %>

<% end %>

app/views/bookings/create.js.erb
// function refreshForm(innerHTML) {
//   const newBookingForm = document.getElementById('new_booking');
//   newBookingForm.innerHTML = innerHTML;
// }

// // function addBooking(bookingHTML) {
// //   const reviewsList = document.getElementById('reviews');
// //   reviewsList.insertAdjacentHTML('beforeend', bookingHTML);
// // }

// function refreshPrice(countHTML) {
//   const priceCount = document.getElementById('booking_price');
//   const totalPrice = document.getElementById('total-price');
//   totalPrice.innerHTML = countHTML;
//   const seats = document.getElementById('booking_seats')
//   let totalPrice = document.getElementById('total-price')
// }

// <% if @booking.save %>

// refreshForm('<%= j render "bookings/bookingform", jet: @jet, booking: Booking.new %>');
// refreshPrice('<%= @booking.booking_price %>');
// <% else %>
// refreshForm('<%= j render "bookings/bookingform", jet: @jet, booking: @booking %>');
// <% end %>

// seats.addEventListener('input', function(e) {
//   totalPrice.innerText = Number(totalPrice.innerText) * Number(e.target.value)
// });

app/views/bookings/edit.html.erb
<div class="container-fluid">
  <div class="edit-container">
    <div class="intro-container">
      <p id="edit-title">Edit booking</p>
    </div>

    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
        <div class="form-edit-booking">
          <%= simple_form_for @booking do |f| %>
              Seats booked:
            <%= f.input :seats, as: :select, collection: @jet.seat_range, autofocus: true, label: false, input_html: { style: "width: 100%" } %>

          <div class="form-actions">
            <%= f.button :submit, "Update" %>
          </div>

          <% end %>

        </div>
      </div>
    </div>
  </div>

  <div id="bottom"></div>
</div>

app/views/bookings/index.html.erb
<h1 class="text-center booking-header">Your Bookings</h1>
<% if @bookings.empty? %>
  <h3 class="text-center no-booking">No bookings yet!</h3>
  <% else %>
  <% @bookings.each do |booking| %>
    <div class="container">
      <div class="row">
        <div class="booking-card">
          <div class="col-xs-12">
            <div class="box">
              <ul class="left">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
              </ul>
              <ul class="right">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
              </ul>
              <div class="ticket">
                <span class="airline"><%= booking.jet.name  %></span>
                <span class="airline airlineslip"><%= booking.jet.name  %></span>
                <span class="boarding">Boarding Pass</span>
                <div class="content">
                  <span class="jfk"><%= booking.jet.airport_origin.acronym %></span>
                  <span class="plane"><?xml version="1.0" ?><svg clip-rule="evenodd" fill-rule="evenodd" height="60" width="60" image-rendering="optimizeQuality" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg"><g stroke="#222"><line fill="none" stroke-linecap="round" stroke-width="30" x1="300" x2="55" y1="390" y2="390"/><path d="M98 325c-9 10 10 16 25 6l311-156c24-17 35-25 42-50 2-15-46-11-78-7-15 1-34 10-42 16l-56 35 1-1-169-31c-14-3-24-5-37-1-10 5-18 10-27 18l122 72c4 3 5 7 1 9l-44 27-75-15c-10-2-18-4-28 0-8 4-14 9-20 15l74 63z" fill="#222" stroke-linejoin="round" stroke-width="10"/></g></svg></span>
                  <span class="sfo"><%= booking.jet.airport_destination.acronym %></span>
                  <span class="jfk jfkslip"><%= booking.jet.airport_destination.acronym %></span>
                  <span class="plane planeslip"><?xml version="1.0" ?><svg clip-rule="evenodd" fill-rule="evenodd" height="50" width="50" image-rendering="optimizeQuality" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg"><g stroke="#222"><line fill="none" stroke-linecap="round" stroke-width="30" x1="300" x2="55" y1="390" y2="390"/><path d="M98 325c-9 10 10 16 25 6l311-156c24-17 35-25 42-50 2-15-46-11-78-7-15 1-34 10-42 16l-56 35 1-1-169-31c-14-3-24-5-37-1-10 5-18 10-27 18l122 72c4 3 5 7 1 9l-44 27-75-15c-10-2-18-4-28 0-8 4-14 9-20 15l74 63z" fill="#222" stroke-linejoin="round" stroke-width="10"/></g></svg></span>
                  <span class="sfo sfoslip"><%= booking.jet.airport_destination.acronym %></span>
                  <div class="sub-content">
                    <span class="name">PASSENGER NAME<br><span><%= booking.user.first_name %></span></span>
                    <span class="flight">FLIGHT N&deg;<br><span>X3-65C3</span></span>
                    <span class="gate">GATE<br><span>11B</span></span>
                    <span class="seat">SEAT<br><span>45A</span></span>
                    <span class="boardingtime">BOARDING TIME<br><span>8:25PM | <%= booking.jet.start_on %></span></span>

                     <span class="flight flightslip">FLIGHT N&deg;<br><span>X3-65C3</span></span>
                      <span class="seat seatslip">SEAT<br><span>45A</span></span>
                     <span class="name nameslip">PASSENGER NAME<br><span><%= booking.user.first_name %></span></span>
                  </div>
                </div>
                <div class="barcode"></div>
                <div class="barcode slip"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-sm-offset-2">
          <% if policy(booking).update? %>
          <%= link_to "Inviting more people?", edit_booking_path(booking) %>
          <% end %>
          <br>

          <!-- CHANGE THIS LINE TO TRIGGER ERROR MESSAGE, SEE DIV AT BOTTOM -->
          <%= fancy_popup_link("Cancel your booking?", target: "fancy-#{booking.id}") %>

        </div>
        <div class="col-xs-12 col-sm-4 col-sm-offset-1">
          <div class="booking-details">
            <p>
              Seats booked: <%= booking.seats %>
              <br>
              Total price: <%= booking.booking_price %>
              <br>
              Host: <%= booking.jet.user.first_name %>
              <br>
              Contact details: <%= booking.jet.user.email %>
              <br>

            </p>
          </div>
        </div>
      </div>
    </div>

  <% end %>
<% end %>

<br>
<br>
<!-- THIS DIV BELOW IS THE CONFIRMATION POP MESSAGE, CHANGE TEXT DEPENDING ON PAGE -->

<% @bookings.each do |booking| %>
  <%= fancy_popup("Are you sure you want to delete this booking?", id: "fancy-#{booking.id}") do %>
    <% if policy(booking).destroy? %>
    <%= link_to "Yes", booking_path(booking), method: :delete %>
    <% end %>
  <% end %>
<% end %>

app/views/jets/_card.html.erb
<div class="card-wrapper">
  <div class="card"
    <% if jet.photo? %>
      style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path jet.photo.url(:thumbnail) %>);"
    <% else %>
      style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));"
    <% end %>
    >
  </div>

    <div class="card-description">
      <h3><%= jet.name %></h3>
      <p>$<%= jet.price %> one way</p>
    </div>
    <%= link_to "", jet_path(jet), class: "card-link"%>
</div>

app/views/jets/_card_jets_index.html.erb
<div class="card-wrapper">
  <div class="card"
    <% if jet.photo? %>
      style="background-image: url(<%= cl_image_path jet.photo.url(:thumbnail) %>); background-position: center;"
    <% else %>
      style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));"
    <% end %>
    >
  </div>

    <div class="card-description">
      <p><%= jet.airport_origin.name %></p>
      <h3><%= jet.name.upcase %></h3>
      <p>from <%= jet.price %> USD</p>
    </div>
    <%= link_to "", jet_path(jet), class: "card-link"%>
</div>

app/views/jets/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
        <div class="form">
        <%= simple_form_for @jet do |f| %>
          <%= f.input :name %>
          <%= f.input :description, class: "form-control-width" %>
          <%= f.input :has_service, as: :select %>
          <%= f.input :max_capacity, collection: 1..10 %>
          <%= f.association :airport_origin %>
          <%= f.association :airport_destination %>
          <%= f.input :price %>
          <%= f.submit "Edit Jet", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/jets/index.html.erb
<div class="container-header">
  <div class="banner">
    <% i = 98 %>
    <% %w(banner2 beach1 image2 moutain1 moutain2 norway1).each do |img| %>
      <%= image_tag "#{img}.jpg", style: "z-index: #{i}" %>
      <% i -= 1 %>
    <% end %>
  </div>
  <div class="search-wrapper">
    <div class="search-bar">
      <h3 class="row-h3">Search for your first trip now:</h3>
      <br>
      <%= form_tag(search_airports_path, method: :get, class: "index-form") do  %>
      <%= select_tag :airport_origin, options_from_collection_for_select(@airports, "id", "code_name") %>
      <%= select_tag :airport_destination, options_from_collection_for_select(@airports, "id", "code_name") %>
      <%= submit_tag 'Search' %>
      <% end %>
    </div>
  </div>
</div>
<div class="body-container">
      <br>
      <br>
      <p class= "index-titles"> Introduction</p>
      <br>
      <div class="multi-tab">
        <div class="tab">
          <button class="tablinks" onclick="openCity(event, 'Paris')">How does it work</button>
          <button class="tablinks" onclick="openCity(event, 'Tokyo')">Book your first trip</button>
        </div>
        <div id="Paris" class="tabcontent">
          <p>Have you ever thought to yourself this line at the airport is taking way too long? Well think no more! With Jet Lag you can rent a jet to fly from point a to point b in the most luxurious and pain free manner.</p>
          <p>Our platform also allows owners of jets to upload their plane when there's space available!</p>
        </div>
        <div id="Tokyo" class="tabcontent">
          <p><%= link_to "Sign up now", new_user_registration_path %> and get ready to fly in style.</p>
        </div>
      </div>
  </div>
</div>
<br>

<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-8">
  <p class= "index-titles"> Jets near you</p>
  <br>
  <br>
  <br>
  <div class="row">
    <% @jets.each do |jet| %>
    <div class="col-xs-12 col-sm-4 col-md-3">
      <%= render "card_jets_index", { jet: jet }%>
    </div>
    <% end %>
      </div>
      </div>
    </div>
<br>
  <div class="btn btn-danger">See more</div>
  <br>
  <br>
  <br>
  <br>
</div>
<%= javascript_pack_tag 'banner' %>

app/views/jets/new.html.erb
<div class="container-fluid">
  <div class="newjet-container">

    <div class="top-container">
      <p class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">Post an Ad</p>
    </div>

    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
        <div class="form-jet">
          <%= simple_form_for @jet do |f| %>
          <%= f.error_notification %>

          <p id="title-steps">1/4 Ad details</p>
          <div class="step-one">
            <%= f.input :name, required: true, autofocus: true, label: "Your jet name" %>
            <%= f.input :description, required: true, label: "Describe your jet", hint: "4000 characters.min" %>

            <div class="select-jet">
              <%= f.input :max_capacity, as: :select, collection: 1..10, required: true, label: "Maximum seats" %>
              <%= f.input :has_service, as: :select, required: true, label: "Is service included?" %>
            </div>
            <div class="select-jet">
              <%= f.association :airport_origin, collection: @airports.map { |a| [a.code_name, a.id] }, required: true, label: "Where is your jet flying from?" %>
              <%= f.association :airport_destination, collection: @airports.map { |a| [a.code_name, a.id] }, required: true, label: "To which destination?" %>
            </div>
          </div>

          <p id="title-steps">2/4 Available Dates</p>
          <div class="step-two">
            <div class="row">
              <div class='col-md-5'>
                <%= f.input :start_on, as: :string, required: true, label: "Available from", input_html: { class: 'datepicker', data: { :'date-start-date' => '+1d'} }  %>
              </div>
              <div class='col-md-5'>
                <%= f.input :end_on, as: :string, required: true, label: "To", input_html: { class: 'datepicker', data: { :'date-start-date' => '+2d'} }  %>
              </div>
            </div>
          </div>

          <p id="title-steps">3/4 Set Price ($USD)</p>
          <div class="step-three">
            <%= f.input :price, required: true, label: "Price" %>
          </div>

          <p id="title-steps">4/4 Add Photos</p>
          <div class="step-four">
            <%= f.input :photo, label: "Upload at least one photo", hint: "High resolution photo drive higher interest!" %>
            <%= f.input :photo_cache, as: :hidden %>
          </div>

          <div class="form-actions-jet">
            <%= f.button :submit, "Post ad" %>
          </div>
        <% end %>
        </div>
      </div>
    </div>

  </div>

  <div id="closing-cross-jet">
    <%= link_to :jets do %>
      <i class="fa fa-times"></i>
    <% end %>
  </div>
</div>

app/views/jets/show.html.erb
  <div class="container-header">
    <div class="banner">
      <%= cl_image_tag @jet.photo, class: 'banner', cloud_name: 'dkovtlfcg' %>
      <h1 class="show-title"><%= @jet.name %></h1>
    </div>
  </div>
  <br>
  <div class="container">
    <p class="show-text">Book your first trip with Jet Lag today:</p>
    <div class="row">
        <div class="jet-card">
          <div>
            <%=image_tag "https://source.unsplash.com/600x700//?{landscape}", class:"inside-image"%>
          </div>
          <div class="description-container">
            <br>
            Service on board: <b><%= @jet.has_service ? "Yes" : "No" %></b>
            <br>
            Belongs to: <b><%= @jet.user.first_name %></b>
            <br>
            Departure airport: <b><%= @jet.airport_origin.name %> (<%= @jet.airport_origin.acronym %>)</b>
            <br>
            Destination airport: <b><%= @jet.airport_destination.name %> (<%= @jet.airport_destination.acronym %>)</b>
            <br>
            Base price: $<span id="base-price"><b><%= @jet.price %><b></span>
              <div class="booking-action">
                <div class="booking-details">
                  <br>
                  <%= render 'bookings/bookingform', :jet => @jet, :booking => @booking, class:"seats-form" %>
                </div>
                <div class="total">
                  Total price: $ <span id="total-price"><%= (@jet.calculate_price).floor %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      <div class="row">
        <% if policy(@jet).update? %>
        <%= link_to "Edit this trip", edit_jet_path(@jet) %>
        <% end %>
        <br>
        <!-- CHANGE THIS LINE TO TRIGGER ERROR MESSAGE, SEE DIV AT BOTTOM -->
        <% if policy(@jet).destroy? %>
          <%= fancy_popup_link("Delete your jet?") %>
        <% end %>
      </div>
    </div>
  </div>

<%= javascript_pack_tag 'total_price' %>

<!-- THIS DIV BELOW IS THE CONFIRMATION POP MESSAGE, CHANGE TEXT DEPENDING ON PAGE -->
<%= fancy_popup("Are you sure you want to delete this trip?") do %>
  <%= link_to "Yes", jet_path(@jet), method: :delete if policy(@jet).destroy? %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links text-center small">
    <a href="https://github.com/jeremycpc/jet-lag"><i class="fa fa-github"></i> Jet Lag's code base is open source</a>
  </div>

  <div class="footer-copyright text-center small">Made with <i class="fa fa-heart"></i> by Jeremy, Florence, Michael and Harrison</div>

</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-container">

<!-- Logo -->
<%= link_to root_path, class: "new-logo" do %>
  <i class="far fa-paper-plane icon"></i>
  <div class="main-title">Jet Lag</div>
<% end %>

<!-- Right Navigation -->
<!--   <div class="navbar-wagon-right hidden-xs hidden-sm"> -->


 <!-- Profile picture with dropdown list -->

<div class="navbar-wagon-item">
  <div class="dropdown">
    <% if current_user %>
     <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: {:toggle => "dropdown"}%>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Create your ad", new_jet_path %></li>
        <li><%= link_to "Show your bookings", bookings_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Update Details", edit_user_registration_path %></li>
      </ul>
    <% else %>
      <div class="btn btn-danger btn-sm" data-toggle= "dropdown">Menu</div>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Log In", user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      </ul>
    <% end %>

  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Open+Sans" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <title>Jet-Lag</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'layouts/navbar' unless devise_controller? %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'layouts/footer' unless devise_controller? %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
  </body>
</html>